dependencies {
    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:NotEnoughItems:2.7.69-GTNH:dev")

    // implementation("org.lwjgl:lwjgl-stb:3.3.3")
    // runtimeOnly("org.lwjgl:lwjgl-stb:3.3.3:natives-windows")
    // runtimeOnly("org.lwjgl:lwjgl-stb:3.3.3:natives-linux")
    // runtimeOnly("org.lwjgl:lwjgl-stb:3.3.3:natives-macos")
    implementation('org.joml:joml:1.10.8')
    implementation("com.google.guava:guava:33.4.8-jre")

    runtimeOnly("com.github.GTNewHorizons:GT5-Unofficial:5.09.51.459:dev")
    runtimeOnly("com.github.GTNewHorizons:ServerUtilities:2.1.61:dev")
    runtimeOnly("com.github.GTNewHorizons:NotEnoughItems:2.7.88-GTNH:dev")
    runtimeOnly("com.github.GTNewHorizons:Angelica:1.0.0-beta56:dev")
    runtimeOnly("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-688-GTNH:dev")
    runtimeOnly("com.github.GTNewHorizons:AppleCore:3.3.7:dev")
}
